CREATE TABLE PERSON
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100) NOT NULL UNIQUE,
    age   int,
    email varchar(100)
);

CREATE TABLE BOOK
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int          REFERENCES PERSON (id) ON DELETE SET NULL,
    title     varchar(100) NOT NULL UNIQUE,
    author    varchar(75)  NOT NULL,
    year      int CHECK (year > 1700),
    picked_at timestamp
);