CREATE TABLE PERSON (
                        person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        year int CHECK (year > 1900)
);

CREATE TABLE BOOK (
                      book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id int REFERENCES PERSON(person_id) ON DELETE SET NULL,
                      name varchar(100) NOT NULL UNIQUE,
                      author varchar(75) NOT NULL,
                      year int CHECK (year > 1700)
);