CREATE TABLE PERSON
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(100) NOT NULL UNIQUE,
    age       int CHECK (age > 0),
    email     varchar(100) UNIQUE,
    date_of_birth DATE,
    created_at timestamp,
    mood INT
--mood VARCHAR если enum type string
);

CREATE TABLE Item
 (
     id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     person_id int          REFERENCES Person (id) ON DELETE SET NULL,
     item_name varchar(100) NOT NULL
 );
